site_name: Claire Nelson
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/claire-nel/clairenelson'
site_url: https://claire-nel.github.io/clairenelson
nav:
  - Home: index.md
  - Analysis of Data Job Market Trends Using Python: code-examples.md
theme:
  name: material
  font:
    text: Merriweather Sans
  palette:

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: cyan
      accent: grey

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: cyan
      accent: white

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark