site_name: Claire Nelson
repo_name: 'Go to GitHub'
repo_url: 'https://github.com/claire-nel/clairenelson'
site_url: https://claire-nel.github.io/clairenelson
nav:
  - Home: index.md
  -  Analysis of Data Job Market Trends Using Python: code-examples.md
  -  My Favorite Python Libraries: favorite-python-libraries.md
  -  Contact: contact.md
  - Currently Studying: currently-studying.md
theme:
  name: material